//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbonlinestoreEntities : DbContext
    {
        public dbonlinestoreEntities()
            : base("name=dbonlinestoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcategory> tblcategories { get; set; }
        public virtual DbSet<tblorder> tblorders { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tblsupplier> tblsuppliers { get; set; }
        public virtual DbSet<tblcompany> tblcompanies { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
        public virtual DbSet<tblstock> tblstocks { get; set; }
        public virtual DbSet<stock_items> stock_items { get; set; }
        public virtual DbSet<myinvoice> myinvoices { get; set; }
    }
}
