//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblproduct()
        {
            this.tblstocks = new HashSet<tblstock>();
        }
    
        public int pid { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> qty { get; set; }
        public string pimage { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<int> itemcode { get; set; }
    
        public virtual tblcategory tblcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstock> tblstocks { get; set; }
    }
}
