//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstock
    {
        public int stockid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> expirary_date { get; set; }
    
        public virtual tblproduct tblproduct { get; set; }
        public virtual tblsupplier tblsupplier { get; set; }
    }
}
