//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int userid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> Roleid { get; set; }
    }
}
